urgent_avoidance_planner:
  ros__parameters:
    search_starting_distance: 3.8 # in meters
    rear_angle_range_min: 120.0 # 0 to 359
    rear_angle_range_max: 240.0 # 0 to 359, larger than rear_angle_range_min
    direction_duration_threshold: 1.5 # in seconds
